Collector's app deployment
test-network-function/collector-deployment pull request #6
Opened 2023-06-05 07:17 UTC by shirmoran

2023-06-07 14:44 UTC, bnshr requested changes

2023-06-07 14:44 UTC, bnshr commented on k8s/collector-deployment.yml
> +            value: "collectoruser:password@tcp(mysql.default.svc.cluster.local:3306)/"
Only DB_URL and DB_PORT should be hard coded here.
The rest like DB_USER, DB_PASSWORD should be inside the secret.
Sample code is mentioned here.

apiVersion: v1
kind: Secret
metadata:
  name: collector-db-creds
type: Opaque
data:
  mysql-username: bnNzZnVzcg==
  mysql-password: bnNzZnBhc3N3ZA==
  mysql-db-name: bnNzZmRi

2023-06-07 14:46 UTC, bnshr commented on k8s/collector-deployment.yml
> +            value: "collectoruser:password@tcp(mysql.default.svc.cluster.local:3306)/"
All the values should be base64 encoded and from the collector app, you have to access by decoding. 
And in the collector deployment you get the env variable values mounting the secret.

2023-06-08 16:51 UTC, shirmoran commented on k8s/collector-deployment.yml
> +            value: "collectoruser:password@tcp(mysql.default.svc.cluster.local:3306)/"
changed

2023-06-09 13:36 UTC, bnshr approved these changes
Lgtm!

2023-06-09 21:54 UTC, sebrandon1 commented on k8s/collector-deployment.yml
> +  mysql-username: Y29sbGVjdG9ydXNlcg==
We might have to come up with a better solution to checking in these values and regenerate the creds for the "real" DB.

2023-06-09 21:54 UTC, sebrandon1 approved these changes

2023-06-09 21:54 UTC, merged